[ENTRY] External communications page
pyOpenSci/handbook pull request #79
Opened 2024-08-13 15:26 UTC by kierisi

Incorporating feedback on the draft from @lwasser, this page includes information on:
* External communications platforms
* The pyOS blog, including how to submit a guest post
* pyOS newsletters
* YouTube
* Discourse
* Zenodo

2024-08-13 15:34 UTC, kierisi commented
pre-commit.ci autofix

2024-09-17 18:13 UTC, lwasser requested changes
This is a great start jesse. 

I left some comments inline. 
id like for each platform to have a section on 

* goals (you have a nice section for the blog but not for other sections)
* metrics of success
* example content that shows tone and strategy. 

The other meta topic is - mailchimp.

2024-09-17 18:13 UTC, lwasser commented on organization/external-communications.md
> +6. Once you have an approving review, the pull request can be merged. In the case of guest blog posts, a member of the pyOpenSci team will merge your post.
```suggestion
6. Once you have an approving review, the pull request can be merged. In the case of guest blog posts, a member of pyOpenSci's staff or contributor team will merge your post.
```

2024-09-17 18:13 UTC, lwasser commented on organization/external-communications.md
> +pyOpenSci has GitHub organization-wide policies in place that ensure all pull requests are generally reviewed prior to being merged. In some instances we may bypass those if the PR is a small fix or
```suggestion
pyOpenSci has GitHub organization-wide policies in place that require all pull requests are reviewed before being merged. In some instances, we may bypass those if the PR is a small fix or critical update. In most cases a review is preferred. 
```

2024-09-17 18:13 UTC, lwasser commented on organization/external-communications.md
> +pyOpenSci has GitHub organization-wide policies in place that ensure all pull requests are generally reviewed prior to being merged. In some instances we may bypass those if the PR is a small fix or
Please do not add language to the handbook that says  "ask Leah". If you are unsure about the policy i'm super happy to chat about it.  But for now, I'm comfortable with saying something like "ask a member of the pyOS staff".

2024-09-17 18:13 UTC, lwasser commented on organization/external-communications.md
> +```
```suggestion

:::{admonition} Yaml elements required for blog posts
:class: tip 

All package authors, maintainers (and users) of a pyOpenSci-accepted package are welcome and encourage to submit a blog post (or series of blog posts) about their review experience and/or the use of the package. When submitting your blog post, please include the following YAML elements:

```
layout: single
title: "The title of your blog post"
excerpt: "One to five sentences summarizing your post. This text will appear on our [blog landing page](https://pyopensci.org/blog)"
author: "Your name"
permalink: /blog/url-for-your-post.html
header:
  overlay_image: images/headers/your-blog-post-header-image.png
  overlay_filter: rgba(20, 13, 36, 0.8)
categories:
  - blog-post
  - community
classes: wide
toc: true
comments: true
---
```
:::
```

2024-09-17 18:13 UTC, lwasser commented on organization/external-communications.md
> +```
i just made this correction here - please check the build to ensure it's correct!

2024-09-17 18:13 UTC, lwasser commented on organization/external-communications.md
> +
```suggestion
In addition to pyOpenSci social outreach, we monitor social media for any personal posts that authors have created. To promote these posts, we will repost.

```

2024-09-17 18:13 UTC, lwasser commented on organization/external-communications.md
> +
i'm not sure the intent of this sentence but I tried to rewrite. Please rewrite as you see fit.

2024-09-17 18:13 UTC, lwasser commented on organization/external-communications.md
> +* A monthly newsletter published on LinkedIn and sent to all Mailchimp subscribers
Flaggin mailchimp. If we made a decision after august 14 that i've forgotten you can remind me!

2024-09-17 18:13 UTC, lwasser commented on organization/external-communications.md
> +The weekly LinkedIn newsletter has three main categories:
This is great! Please add an example of how each of these posts is structured . 

then please also add what metrics are used to track success of these items. each section should include goals of the platform, target audience, metrics of success.

2024-09-18 21:29 UTC, kierisi commented on organization/external-communications.md
> +### Mailchimp
it didn't - this PR went up before then! I'll go through and make adjustments.

2024-09-19 15:53 UTC, kierisi commented on organization/external-communications.md
> +[HubSpot](https://hubspot.com/) is pyOpenSci's customer relationship management (CRM) platform. Although HubSpot has email capabilities, pyOpenSci does not currently use this functionality.
yep! related to the above, the PR was written and submit before we discussed these changes.

2024-09-19 16:37 UTC, kierisi commented on organization/external-communications.md
> +4. Make sure that the blog post passes CI checks that look for spelling errors, broken links and more. Please note that occasionally the `htmlproofer` check will fail because the URL does not exist y
will do! I'm going to submit this PR for review, and then once the htmlproofer PR is complete and merged, will submit a patch to link to it here.

2024-09-19 18:48 UTC, lwasser commented on organization/external-communications.md
> +### Mailchimp
Fantastic. thanks!

2024-09-19 20:52 UTC, closed without merging