IMAGE: failing CI
pyOpenSci/handbook pull request #87
Opened 2024-08-22 20:47 UTC by kierisi

Added an image to the handbook showing what the red "X" looks like for a failing CI check.

2024-08-22 21:24 UTC, lwasser requested changes

2024-08-22 21:24 UTC, lwasser commented on community/github/continuous-integration.md
> +![When a CI check fails, you'll see a red 'X' next to the CI check that hasn't passed](/images/ci-images/contributor-ci-fail.png)
@kierisi it's important that all of our documented are accessible. As such please add both an alt tag for accessibility and a caption. Here i think this is a caption, but it actually reads as an alt tag in the html rendered page. 

You can either look at the myst markdown documentation for how to do this or look at how we add images in the packaging guide for guidance.

2024-08-29 17:03 UTC, lwasser approved these changes

2024-09-06 16:17 UTC, kierisi commented
@lwasser should be fixed! thanks to @tracykteal and @rich-iannone for the assist on this one!

2024-09-16 19:26 UTC, lwasser approved these changes

2024-09-16 19:26 UTC, merged