added a PR checklist to the GitHub pull requests section
pyOpenSci/handbook pull request #90
Opened 2024-09-04 21:09 UTC by kierisi

added a PR checklist, as discussed with @lwasser. this list can be expanded upon, but represents a good initial set of checks for individuals to use when contributing to a pyopensci repository.

2024-09-04 23:12 UTC, kierisi commented
pre-commit.ci autofix

2024-09-17 18:17 UTC, lwasser commented on community/github/pull-requests.md
> +The following checklist might be helpful in reviewing your own PR. This checklist is what we use internally before submitting a PR, in order to help ensure things go as smoothly as possible:
```suggestion
Please follow this pull request review checklist when submitting a PR to the pyOpenSci GitHub repository. This checklist will both make the pull request review process easier both for you as the PR author and the repository maintainers. It also will make the pull request merge process more smooth and efficient. 
```

2024-09-17 18:19 UTC, lwasser commented on organization/canva.md
> +# pyOpenSci uses Canva as a shared graphic platform
Is the cCanva content in this PR intentional? there is a merge conflict with it (we merged #74 ) in this PR.

2024-09-17 18:20 UTC, lwasser requested changes
@kierisi i haven't left a full set of comments. there is a merge conflict on this PR and also I don't know if you meant to add the canva page to this PR. can you please rebase this branch off of main and determine whether the canva page is intentional or not? I will then continue to review the content here. Feel free to address the few comments that i've already suggested and then ping me here to review again.

2024-09-19 15:43 UTC, closed without merging

2024-09-19 15:44 UTC, kierisi commented
closing in favor of #91